### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [GA114/tc359p2#1]
:+1: :tada:  Wow, I love it. I laughed so hard at the examples that I startled my cat. :smiley: Here are a couple other little details I'd like to give you kudos for:

- frequent commits that tell a real story about how this software was developed
- the URL file so that people visiting the repo can see where it's hosted

Now, **nothing here needs to be changed**, but I always try to find some room for improvement. So here are a few tips I would give a colleague on a code review. None of these are things you're expected to know already - it's just nitpicky details meant to help improve your projects in the future and make you an even stronger Ruby developer.

### Remove the `views/index.html` file

Since it's never actually served to the user, I would simply delete the `index.html` and that commit that deletion to git, like so:

``` bash
rm views/index.html
git add -u views/index.html # This -u options allows the removal to be staged for a commit
git commit -m "removed unused index.html file"
```

### Indent with 2 spaces instead of 4

In Ruby projects, it's standard to indent with 2 spaces instead of 4. This is also the most common convention for HTML files. I realize the standard for Python (which you're probably more used to) is 4 spaces, but you can change the indentation rules for specific file types [in vim like this](http://vim.wikia.com/wiki/Indenting_source_code#Different_settings_for_different_file_types).

### Add the `log` file to a `.gitignore` file

When a `.gitignore` file is included in the root of a project managed by git, any files (or file patterns) listed in that file are ignored by git. Below is the contents of the `.gitignore` file I would use in your case and here's [another example from another sinatra app](https://github.com/anynines/ruby-sinatra-example-app/blob/master/.gitignore).

``` gitignore
log
```

To then remove that file from your git repo, you can [follow these instructions](http://stackoverflow.com/questions/1139762/ignore-files-that-have-already-been-committed-to-a-git-repository#answer-1139797).

### Indent your HTML consistently

I noticed that in each `.html` file, the first line within the body wasn't indented like the ones below it. I would keep that line at the same indentation level as the lines below it, since they're all direct children of the body element.

This doesn't effect the way the HTML renders, but it's nicer for other programmers to look at.

### Add documentation in a `README.md` file, rather than in commits

I'm referring to [this commit specifically](https://github.com/GA114/tc359p2/commit/158231a35999e645b29ee55ec2bf44b55fcbb826):

``` text
"curl `cat URL`". UUOC, maybe, but whatever.
```

Users typically look for documentation on a project in a `README.md` file, which GitHub automatically interprets and places below you file list if it's in the project's root directory. [Here's an example](https://github.com/chrisvfritz/farmers_markets) of a sinatra app with [a `README.md` file](https://raw.githubusercontent.com/chrisvfritz/farmers_markets/master/README.md).

The `.md` file extension refers to **Markdown**, which is a wonderfully simple markup language used all over GitHub and in many other developer communities. In fact, I'm writing in Markdown right now! I recommend taking a quick glance at [GitHub's Markdown Basics](https://help.github.com/articles/markdown-basics/) if you're not already familiar with it.

### Use rake for common tasks

For command-line tasks you might want to perform often, it's typical in Ruby projects to manage these with a gem called **rake**. To set up rake for a project, you can do this:

``` bash
echo "gem 'rake'" >> Gemfile # Append gem 'rake' to the end of your Gemfile
bundle install               # Install newly added gems in the Gemfile
bundle binstubs rake         # Install the rake binstub to ./bin/rake
touch Rakefile               # Create a file called Rakefile
```

Then you'll add specific "tasks" to you `Rakefile`. These are useful for automating complex tasks related to your project and also for separating the exact implementation of a task from the task itself. Let's take a look at this example Rakefile:

``` ruby
task :url do
  system 'cat URL'
end

namespace :url do
  task :get do
    system 'curl `cat URL`'
  end
  task :download do
    system 'wget `cat URL`'
  end
end
```

The first 3 lines are essentially saying, "When I type in `rake url` from my project directory, run `cat URL` in bash.

We've also set up `url` as a namespace with a couple tasks within it. This allows users to perform other actions with the url. Now they can type `rake url:get` or `rake url:download` to run the corresponding commands. 

With these simple, one-line commands, this might seem like a lot of work for nothing. It becomes much more useful however when you begin to modify your commands, mix in more Ruby, and make them more complex. For example, I can definitely imagine this `Rakefile` starting to grow into something more like this:

``` ruby
TEMP_PATH = 'tmp'

task :url do
  system 'cat URL'
end

namespace :url do

  task :get do
    system 'curl `cat URL`'
  end

  task :download, :filename do |tsk, args|
    args.with_defaults(
      filename: 'out.html'
    )

    filepath = "#{TEMP_PATH}/#{args[:filename]}"

    system "mkdir #{TEMP_PATH}"
    system "curl -L `cat URL` > #{filepath}"
    system "cat #{filepath}"
  end

end

task :clean do
  system 'rm -rf tmp'
end
```

And even though we've made all these changes and added more code, we still only have to remember `rake url:download` - now with an optional parameter to specify filename. If other developers are also working on the project, they also reap the benefits of not having to understand all the changes you made on the backend in order to continue using these tools.

## Great work

Once again, great work on this! None of the changes above are things you should already know or need to incorporate into this project. It's just me trying to give you more space to grow.

**Comment by GA114** [comment]
Oh, no, these tips are all excellent, and extremely thorough! I *was* sloppy in a few places, and I *should* know better than to document my actions in commit messages—still, live and learn! I'll apply the changes in tc359p3.

I'm also glad you appreciated my wackiness; tell the cat I said "sorry". :stuck_out_tongue_closed_eyes:
